<!DOCTYPE html>
<html>
<head>
	<title>XOX Game</title>
	<link rel="stylesheet" type="text/css" href="./style.css">
</head>
<body>
<form action="#" method="post">
	<input type="hidden" value="">
	<table border="2px" >
		<tr>
			<td>
				<input type="hidden" value="">
				<input type="submit" name="1" value="">
			</td>
			<td>
				<input type="hidden" value="">
				<input type="submit" name="2" value="">
			</td>
			<td>
				<input type="hidden" value="">
				<input type="submit" name="3" value="">
			</td>
		</tr>
		<tr>
			<td>
				<input type="hidden" value="">
				<input type="submit" name="4" value="">
			</td>
			<td>
				<input type="hidden" value="">
				<input type="submit" name="5" value="">
			</td>
			<td>
				<input type="hidden" value="">
				<input type="submit" name="6" value="">
			</td>
		</tr>
		<tr>
			<td>
				<input type="hidden" value="">
				<input type="submit" name="7" value="">
			</td>
			<td>
				<input type="hidden" value="">
				<input type="submit" name="8" value="">
			</td>
			<td>
				<input type="hidden" value="">
				<input type="submit" name="9" value="">
			</td>
		</tr>
	</table>
</form>
</body>
</html>